ALTER TABLE public.team_applications
  ADD COLUMN IF NOT EXISTS is_social_name boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS person_type text NOT NULL DEFAULT 'fisica',
  ADD COLUMN IF NOT EXISTS sex text,
  ADD COLUMN IF NOT EXISTS cpf text,
  ADD COLUMN IF NOT EXISTS rg text,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS profession text,
  ADD COLUMN IF NOT EXISTS phone_landline text,
  ADD COLUMN IF NOT EXISTS cellphone text,
  ADD COLUMN IF NOT EXISTS country text DEFAULT 'Brasil',
  ADD COLUMN IF NOT EXISTS cep text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS street text,
  ADD COLUMN IF NOT EXISTS number text,
  ADD COLUMN IF NOT EXISTS district text,
  ADD COLUMN IF NOT EXISTS complement text,
  ADD COLUMN IF NOT EXISTS bank_name text,
  ADD COLUMN IF NOT EXISTS bank_agency text,
  ADD COLUMN IF NOT EXISTS bank_account text,
  ADD COLUMN IF NOT EXISTS pix_type text,
  ADD COLUMN IF NOT EXISTS pix_key text,
  ADD COLUMN IF NOT EXISTS allow_email_campaigns boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allow_system_emails boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS pref_email boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS pref_sms boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS pref_whatsapp boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS professional_areas jsonb NOT NULL DEFAULT '[]'::jsonb;